"""
Constants for face recognition and camera modules.
Centralizes all magic numbers and configuration values.
"""

# Camera Configuration
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 480
DEFAULT_FPS = 30
CAMERA_INIT_TIMEOUT_SECONDS = 5

# Face Detection
MIN_FACE_WIDTH = 100
MIN_FACE_HEIGHT = 100
MIN_FACE_SIZE = (MIN_FACE_WIDTH, MIN_FACE_HEIGHT)
FACE_PADDING_PIXELS = 20
FACE_DETECTION_SCALE_FACTOR = 1.1
FACE_DETECTION_MIN_NEIGHBORS = 5

# Image Quality
QUALITY_THRESHOLD = 0.50
MIN_QUALITY_SCORE = 0.40
SHARPNESS_WEIGHT = 0.4
CONTRAST_WEIGHT = 0.3
BRIGHTNESS_WEIGHT = 0.3
CENTER_WEIGHT = 0.3
OPTIMAL_BRIGHTNESS = 128
SHARPNESS_NORMALIZATION_FACTOR = 500.0

# Face Recognition
RECOGNITION_TOLERANCE_STRICT = 0.5
RECOGNITION_TOLERANCE_NORMAL = 0.6
RECOGNITION_TOLERANCE_RELAXED = 0.7
DEFAULT_RECOGNITION_TOLERANCE = RECOGNITION_TOLERANCE_NORMAL

# Frame Processing
FRAME_SKIP_COUNT = 2
FRAME_INTERVAL = 5
MAX_RECOGNITION_FRAMES = 90
MAX_CAPTURE_FRAMES = 150

# Encoding
ENCODING_BATCH_SIZE = 32
ENCODING_MODEL_CNN = "cnn"
ENCODING_MODEL_HOG = "hog"
DEFAULT_ENCODING_MODEL = ENCODING_MODEL_HOG

# Cache Configuration
ENCODING_CACHE_MAX_SIZE = 100
ENCODING_CACHE_TTL_SECONDS = 300

# Photo Capture
DEFAULT_PHOTO_COUNT = 5
MIN_PHOTO_COUNT = 1
MAX_PHOTO_COUNT = 10

# Aspect Ratio Validation
MIN_ASPECT_RATIO = 0.7
MAX_ASPECT_RATIO = 1.3
